
services:
  app:
    image: ghcr.hamdocker.ir/starco76/text_share:6
    container_name: text_sharer_app
    restart: unless-stopped
    networks:
      - text_network

  nginx:
    image: nginx:stable-alpine
    container_name: text_sharer_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - text_network
networks:
  text_network:
    driver: bridge
